import Head from "next/head";
import { UseState } from "components/Home";
import { ClassState } from "components/Home";

export default function Home() {
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <UseState name="UseState" />
      <ClassState name="ClassState" />
    </div>
  );
}
